name: Sermonnotes
options:
  bundleIdPrefix: com.shimondeitel.sermonlog
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Sermonnotes:
    type: application
    platform: iOS
    sources:
      - path: Sermonnotes
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.sermonlog
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Sermonnotes/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  SermonnotesTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: SermonnotesTests
      - path: Sermonnotes.storekit
    dependencies:
      - target: Sermonnotes
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.sermonlog.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  SermonnotesUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: SermonnotesUITests
    dependencies:
      - target: Sermonnotes
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.sermonlog.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Sermonnotes:
    build:
      targets:
        Sermonnotes: all
        SermonnotesTests: [test]
        SermonnotesUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: Sermonnotes.storekit
    test:
      config: Debug
      storeKitConfiguration: Sermonnotes.storekit
      targets:
        - SermonnotesTests
        - SermonnotesUITests
    archive:
      config: Release
